### ISSUE TITLE
Can't start shiny app using this build pack.

### ISSUE THREAD

**Issue by flop71** [beibeiyang/cf-buildpack-r#2]
Hi I'm using your build pack to create a CF shiny dashboard. I have the R application running locally, however when i run the cf push. I get so far but the application fails to launch. I'm seeing the following line in the logs:

2017-08-16T12:14:53.54+0100 [APP/PROC/WEB/0] ERR [Previously saved workspace restored]
   2017-08-16T12:14:53.82+0100 [APP/PROC/WEB/0] OUT > library(shiny)  
   2017-08-16T12:14:53.82+0100 [APP/PROC/WEB/0] ERR Error in library(shiny) : there is no package called ‘shiny’
   2017-08-16T12:14:53.82+0100 [APP/PROC/WEB/0] ERR Execution halted

I also see an occasional message related to init.R

   2017-08-16T12:11:54.10+0100 [STG/0] ERR cat: /tmp/app/init.r: No such file or directory

[august.zip](https://github.com/beibeiyang/cf-buildpack-r/files/1227975/august.zip)

I've attached my project folder. for reference. 

Thanks
Jonathan

**Comment by at062084** [comment]
init.R should be called init.r, no?

**Comment by flop71** [comment]
Excellent catch. I renamed the file to a lower case .r. the command appears to run a lot further. While the R libraries appear to get downloaded and installed, this process appears to loop. 

I receive a generic error message after 15 minutes:


FAILED
Error restarting application: august failed to stage within 15.000000 minutes

**Comment by at062084** [comment]
same error here. changed the code in init.r
 
important difference to original is the part:
         dependencies = c("Depends", "Imports")
This reduces the number of additional packages that are installed after creation of the container.
 
 
.....
my_packages = c("shiny","Cairo")
 
install_if_missing = function(p) {  if (p %in% rownames(installed.packages()) == FALSE) {    install.packages(p, dependencies = c("Depends", "Imports"))  }  else {    cat(paste("Skipping already installed package:", p, "\n"))  }}invisible(sapply(my_packages, install_if_missing))
 
 
regards
Thomas
 
----- Original message -----From: flop71 <notifications@github.com>To: beibeiyang/cf-buildpack-r <cf-buildpack-r@noreply.github.com>Cc: Thomas Strehl <thomas.strehl@at.ibm.com>, Comment <comment@noreply.github.com>Subject: Re: [beibeiyang/cf-buildpack-r] Can't start shiny app using this build pack. (#2)Date: Fri, Sep 8, 2017 2:30 PM 
Excellent catch. I renamed the file to a lower case .r. the command appears to run a lot further. While the R libraries appear to get downloaded and installed, this process appears to loop.
I receive a generic error message after 15 minutes:
FAILEDError restarting application: august failed to stage within 15.000000 minutes

**Comment by beibeiyang** [comment]
Hi Jonathan,

The timeout environment variables CF_STAGING_TIMEOUT and CF_STARTUP_TIMEOUT should only be defined in the command line (in your local OS). Define these variables before the `cf push`. For example, in Linux:

```
$ export CF_STAGING_TIMEOUT=60
$ export CF_STARTUP_TIMEOUT=60
$ cf push
```

I was able to push your app with `my_packages = c("shiny","Cairo")`

```
requested state: started
instances: 1/1
usage: 128M x 1 instances
urls: august-test.cfapps.io
last uploaded: Mon Sep 25 13:32:20 UTC 2017
stack: cflinuxfs2
buildpack: https://github.com/beibeiyang/cf-buildpack-r.git

     state     since                    cpu    memory          disk           details
#0   running   2017-09-25 09:35:22 AM   0.0%   38.7M of 128M   304.7M of 1G
```

Regards,

Beibei

**Comment by flop71** [comment]
Many thanks Beibei!

I will give this another try.

Jonathan Dunne,
PhD Candidate,
Hamilton Institute,
Maynooth University.

**Comment by beibeiyang** [comment]
I will therefore close this ticket. Let me know if you experience any further issues. Thanks!
